/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rmi.ui;

import com.rmi.client.Core;
import com.rmi.interfaces.ClientInterface;
import com.rmi.interfaces.ServerInterface;

import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTextArea;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;

/**
 * 
 * @author root
 */
public class Home extends javax.swing.JFrame {

	/**
	 * Creates new form Home
	 */
	Core core;
	public String name = null;

	public String getName() {
		return name;
	}

	RegUser reg;

	public RegUser getReg() {
		return reg;
	}

	Home home;

	public Home getHome() {
		return home;
	}

	public void closeWindow() {
		getReg().setVisible(true);
		getHome().setVisible(false);
	}

	public Home(ServerInterface server, String name, RegUser reg)
			throws RemoteException {
		setResizable(false);
		setTitle("PowerChat");
		addWindowListener(new WindowAdapter() {
			@Override
			public void windowClosed(WindowEvent e) {
//				System.out.print("close............");
			}

			@Override
			public void windowClosing(WindowEvent e) {
				getReg().setVisible(true);
				try {
					core.logout(getName());
					getReg().setVisible(true);
				} catch (RemoteException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
			}
		});
		initComponents();
//		System.out.print("init home");
		this.home = this;
		this.reg = reg;
		this.name = name;
		core = new Core(name, server, this);
		setSize(371, 553);
		setLocationRelativeTo(null);
//		setOnlineUser(null);
	}

	public void setOnlineUser(ArrayList<String> names) {
		txtOnlineUsers.setText("");
//		System.out.print(names.size());
		try {
			int i = 0;
			while (i < names.size()) {
				txtOnlineUsers.append("\n"+names.get(i++).toString());
			}
		} catch (Exception e) {
			// TODO Auto-generated catch block
			txtOnlineUsers.setText("Online Users.... \n\nNo one online");
			e.printStackTrace();
		}
	}

	public void setMsg(String msg) {
		txtChat.append("\n" + msg);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		txtChat = new javax.swing.JTextArea();
		txtChat.setEditable(false);
		txtMsg = new javax.swing.JTextField();
		txtMsg.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				try {
					// TODO add your handling code here:
					// String msg = txtMsg.getText();
					// txtChat.append("\nme:" + msg);
					core.sendMsg(name + ":" + txtMsg.getText());
					txtMsg.setText("");
				} catch (RemoteException ex) {
					txtChat.append("\nServer is out of reach....");
					txtMsg.setText("");
					Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});
		btnSend = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(0, 0, 0));

		txtChat.setBackground(new java.awt.Color(0, 0, 0));
		txtChat.setColumns(20);
		txtChat.setForeground(new java.awt.Color(0, 255, 51));
		txtChat.setRows(5);
		jScrollPane1.setViewportView(txtChat);

		btnSend.setText("Send");
		btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btnSendMouseClicked(evt);
			}
		});
		btnSend.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnSendActionPerformed(evt);
			}
		});

		txtOnlineUsers = new JTextArea();
		txtOnlineUsers.setEditable(false);
		txtOnlineUsers.setForeground(Color.RED);
		txtOnlineUsers.setBackground(Color.BLACK);
		
		JLabel lblOnlineUsers = new JLabel("Online Users");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1Layout.setHorizontalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
								.addComponent(lblOnlineUsers)
								.addComponent(txtOnlineUsers, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE))
							.addPreferredGap(ComponentPlacement.RELATED))
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(txtMsg, GroupLayout.PREFERRED_SIZE, 183, GroupLayout.PREFERRED_SIZE)
							.addGap(18)
							.addComponent(btnSend)))
					.addGap(1))
		);
		jPanel1Layout.setVerticalGroup(
			jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
					.addContainerGap()
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 422, GroupLayout.PREFERRED_SIZE)
						.addGroup(jPanel1Layout.createSequentialGroup()
							.addComponent(lblOnlineUsers)
							.addPreferredGap(ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
							.addComponent(txtOnlineUsers, GroupLayout.PREFERRED_SIZE, 390, GroupLayout.PREFERRED_SIZE)))
					.addPreferredGap(ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
						.addComponent(txtMsg, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnSend))
					.addGap(18))
		);
		jPanel1.setLayout(jPanel1Layout);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel1,
										GroupLayout.PREFERRED_SIZE, 343,
										GroupLayout.PREFERRED_SIZE)
								.addContainerGap(60, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jPanel1,
										GroupLayout.DEFAULT_SIZE, 505,
										Short.MAX_VALUE).addContainerGap()));
		getContentPane().setLayout(layout);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnSendMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btnSendMouseClicked
		try {
			// TODO add your handling code here:
			// String msg = txtMsg.getText();
			// txtChat.append("\nme:" + msg);
			core.sendMsg(name + ":" + txtMsg.getText());
			txtMsg.setText("");
		} catch (RemoteException ex) {
			txtChat.setText("Server is out of reach....");
			Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_btnSendMouseClicked

	private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSendActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_btnSendActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	// public static void main(String args[]) {
	// /* Set the Nimbus look and feel */
	// //<editor-fold defaultstate="collapsed"
	// desc=" Look and feel setting code (optional) ">
	// /* If Nimbus (introduced in Java SE 6) is not available, stay with the
	// default look and feel.
	// * For details see
	// http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	// */
	// try {
	// for (javax.swing.UIManager.LookAndFeelInfo info :
	// javax.swing.UIManager.getInstalledLookAndFeels()) {
	// if ("Nimbus".equals(info.getName())) {
	// javax.swing.UIManager.setLookAndFeel(info.getClassName());
	// break;
	// }
	// }
	// } catch (ClassNotFoundException ex) {
	// java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (InstantiationException ex) {
	// java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (IllegalAccessException ex) {
	// java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	// java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE,
	// null, ex);
	// }
	// //</editor-fold>
	//
	// /* Create and display the form */
	// java.awt.EventQueue.invokeLater(new Runnable() {
	// public void run() {
	// new Home().setVisible(true);
	// }
	// });
	// }
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnSend;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextArea txtChat;
	private javax.swing.JTextField txtMsg;
	private JTextArea txtOnlineUsers;
}
